spring:
  datasource:
    url: jdbc:oracle:thin:@breadandboard.cn3lqnky3avv.us-east-1.rds.amazonaws.com:1521:ORCL
    username: bandbProject2
    password: breadandboard
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect